[workspace]
members = ["core", "rust_executor", "python_executor", "js_executor"]

[workspace.package]
version = "0.1.0"
edition = "2021"
resolver = "2"

[workspace.dependencies]
autogen_core = { path = "core" }
