[package]
name = "native_executor"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
autogen_core = { workspace = true }

[lints]
rust = { unused_variables = "allow", dead_code = "allow" }